name: Hibernate sample tests

on:
  push:
    branches: [ main ]
    paths:
      - 'examples/**'
      - 'dialect/**'
      - '.github/workflows/java-hibernate-tests.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/**'
      - '.github/workflows/java-hibernate-tests.yml'
  # Give us a button to allow running the workflow on demand for testing.
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual Workflow Run'
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      # Explicitly set permissions, following the principle of least privilege
      actions: read
      checks: write
      pull-requests: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
   
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'corretto'
        architecture: x64
        cache: maven

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.HIBERNATE_IAM_ROLE }}
        aws-region: us-east-1

    - name: Build dialect
      working-directory: ./dialect
      env:
        CLUSTER_ENDPOINT: ${{ secrets.HIBERNATE_DIALECT_INTEGRATION_CLUSTER_ENDPOINT }}
        REGION: ${{ secrets.HIBERNATE_DIALECT_INTEGRATION_CLUSTER_REGION }}
        RUN_INTEGRATION: "TRUE"
      run: |
        ./gradlew build -i
        mvn install:install-file \
          -Dfile=build/libs/aurora-dsql-hibernate-dialect-1.0.0.jar \
          -DgroupId=software.amazon.dsql \
          -DartifactId=aurora-dsql-hibernate-dialect \
          -Dversion=1.0.0 \
          -Dpackaging=jar

    - name: Run sample application tests with dialect JAR
      working-directory: ./examples/pet-clinic-app
      run : |
        mvn validate
        mvn initialize
        mvn clean compile
        mvn test
