name: Deploy to Maven Central
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Manual Publish'
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Deploy to Central Portal
        working-directory: ./dialect
        run: ./gradlew jreleaserDeploy
        env:
          JRELEASER_MAVENCENTRAL_STAGE: 'UPLOAD'
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
          JRELEASER_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          JRELEASER_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
